version: '2'
services:
  #################### Base  ####################

  base: &base
    build: .
    volumes:
      - .:/home/app/app

  #################### CONTAINERS ####################
  kirby_app:
    <<: *base
    container_name: kirby_app
    command: pipenv run python ./manage.py runserver 0.0.0.0:8000
    ports:
      - 127.0.0.1:8000:8000

  kirby_dev:
    <<: *base
    container_name: kirby_dev
    command: pipenv run /bin/bash
